[tool.poetry]
name = "bagstore"
version = "0.1.0"
description = ""
authors = ["viktor d <10xl.pro@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.0.6"
selenium = "^4.22.0"
python-dotenv = "^1.0.1"
psycopg2 = "^2.9.9"
pillow = "^10.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
